version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
      - sandbox.env
    depends_on:
      - db
      - mail
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: mark
      POSTGRES_DB: open-poen-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025  # SMTP server
      - 8025:8025  # Web UI
volumes:
  postgres_data: