FROM python:3.11.0-bullseye
MAINTAINER Spheer.ai <markdewijk@spheer.ai>

RUN echo "Europe/Amsterdam" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# nl_NL.UTF-8 UTF-8/nl_NL.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales

# Libraries that Weasyprint requires and the font that is used for rendering reports.
RUN apt install -y libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 fonts-open-sans

WORKDIR /app

COPY poetry.lock /app/
COPY pyproject.toml /app/
COPY README.md /app/
COPY open_poen_api /app/open_poen_api
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install

CMD ["poetry", "run", "uvicorn", "open_poen_api:app", "--reload", "--port", "8000", "--host", "0.0.0.0"]