version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env
      - mail.env
    depends_on:
      - db
      - mail
      - azurite
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: mark
      POSTGRES_DB: open-poen-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    entrypoint: ["azurite-blob", "--blobHost", "0.0.0.0", "--blobPort", "10000", "-l", "data", "-d", "data/debug_logs.txt"]
    ports:
      - 10000:10000
    volumes:
      - ./azurite_data:/opt/azurite/data

volumes:
  postgres_data:
